s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
s,s,s,s,s,s,s,p,p,p,p,s,s,s,s,s,s,s,s,s,s,p,p,p,p,s,s,s,s,s,s,s
s,s,s,s,s,s,s,s,s,s,s,s,s,p,p,p,p,p,p,s,s,s,s,s,s,s,s,s,s,s,s,s
s,s,s,p,p,p,p,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,p,p,p,p,s,s,s
s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
g,g,g,s,s,s,s,p,p,p,p,s,s,s,s,s,s,s,s,s,s,p,p,p,p,s,s,s,s,g,g,g
d,d,g,g,g,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,g,g,g,d,d
d,d,d,d,g,g,g,s,s,s,s,p,p,p,p,s,s,p,p,p,p,s,s,s,s,g,g,g,d,d,d,d
d,d,d,d,d,d,g,g,g,s,s,s,s,s,s,s,s,s,s,s,s,s,s,g,g,g,d,d,d,d,d,d
d,d,d,d,d,d,d,d,g,g,g,s,s,s,s,p,p,s,s,s,d,g,g,g,d,d,d,d,d,d,d,d
d,d,d,d,d,d,d,d,d,d,g,g,g,s,s,s,s,s,s,g,g,g,d,d,d,d,d,d,d,d,d,d
d,d,d,d,d,d,d,d,d,d,d,d,g,g,g,s,s,g,g,g,d,d,d,d,d,d,d,d,d,d,d,d
d,d,d,d,d,d,d,d,d,d,d,d,d,d,d,h,h,d,d,d,d,d,d,d,d,d,d,d,d,d,d,d
d,d,d,d,d,d,d,d,d,d,d,d,d,d,d,h,h,d,d,d,d,d,d,d,d,d,d,d,d,d,d,d
